env:
  browser: true
  es2021: true
plugins:
  - vue
  - '@typescript-eslint'
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
  - 'prettier'
parserOptions:
  ecmaVersion: 12
rules: {}
